version: "3"

services:
  master_server:
    build: master_server/
    restart: always
    ports:
      - 127.0.0.1:8001:8001
    networks:
      - default

  secondary_server_v1:
    build: secondary_server_v1/
    restart: always
    ports:
      - 127.0.0.2:8002:8002
    networks:
      - default


  secondary_server_v2:
    build: secondary_server_v2/
    restart: always
    ports:
      - 127.0.0.3:8003:8003
    networks:
      - default


#networks:
#  server:
#    driver: overlay # custom-driver-1